import type { ExamData } from "../../exam-data";

export const examData: ExamData = {
  title: "MOCK TEST 04",
  questions: [
    {
      id: 1,
      question: "The APU MASTER SW FAULT light will illuminate:",
      options: [
        "When APU low oil pressure is detected.",
        "When an automatic shutdown of the APU occurs.",
        "For an APU overheat or APU fire.",
        "If the batteries are selected OFF while the APU is operating.",
      ],
      answer: 1,
      image: "https://cms-cdn.classplus.co/parserImages/aab29326-e5c1-4d46-98fd-3ed14984e512.jpg",
    },
    {
      id: 2,
      question:
        "What is the maximum altitude at which the APU may be started using the batteries only?",
      options: ["15, 000 ft", "20, 000 ft", "25, 000 ft", "39, 000 ft"],
      answer: 2,
    },
    {
      id: 3,
      question: "normally how is fuel supplied to the apu?",
      options: [
        "left side fuel line of the a320",
        "left wing tank",
        "center tank",
        "none of the above",
      ],
      answer: 0,
    },
    {
      id: 4,
      question: "APU BLEED Max altitude to assist engine start?",
      options: ["20 000 ft", "22 500 ft", "15 000 ft", "39 000 ft"],
      answer: 0,
    },
    {
      id: 5,
      question: "APU flap is not open and you have pressed the start button?",
      options: [
        "APU will not start",
        "as in a, APU will start after the flap opens",
        "none of the above",
        "APU will have to be started again once flap opens",
      ],
      answer: 1,
    },
    {
      id: 6,
      question: "LOW ENERGY AURAL ALERT is generated by ?",
      options: ["FMGC", "ADIRS", "FAC", "ELAC"],
      answer: 2,
    },
    {
      id: 7,
      question: "IRS IN ALIGN X MN This memo pulses in green?",
      options: [
        "if the alignment of one IRS is faulty",
        "if the alignment of one IRS is not done and engines started",
        "at least one active IRS is being aligned.",
        "memo never pulses in green",
      ],
      answer: 0,
    },
    {
      id: 8,
      question: "After three consecutive APU start attempts?",
      options: [
        "the flight crew must wait 30 min before a new start attempt.",
        "no limitation",
        "the flight crew must wait 60 min before a new start attempt.",
        "three consecutive start attempts are not allowed.",
      ],
      answer: 2,
    },
    {
      id: 9,
      question:
        "What happens when Engine Anti Ice is switched ON, with the aircraft still on the ground ?",
      options: [
        "E. ANTI ice opens for 30 secs on the ground",
        "does not open on the ground",
        "operates as per the position of the E.ANTI ICE pb switch",
        "none of the above",
      ],
      answer: 2,
    },
    {
      id: 10,
      question: "Maximum operating altitude with slats and/or flaps extended?",
      options: ["20 500 ft", "20 000 ft", "25 000 ft", "no limitation"],
      answer: 1,
    },
    {
      id: 11,
      question:
        "when the eng anti ice pb is selected on, which SD page displays the indication?",
      options: [
        "BLEED PAGE",
        "COND PAGE",
        "ENG PAGE",
        "E.ANTI ICE ind is not displayed on any SD page(only on the E.WD)",
      ],
      answer: 3,
    },
    {
      id: 12,
      question:
        "What happens when the INNER TANKS fuel level reaches the underfull sensors?",
      options: [
        "outer tank trnsfr valves open",
        "ecam fuel low level",
        "ctr tank starts supplying fuel if there is fuel in the center tank.",
        "X FEED needs to be used",
      ],
      answer: 2,
    },
    {
      id: 13,
      question: "A reduced thrust take off is done ?",
      options: [
        "to reduce take of distance",
        "to reduce take of run",
        "to increase engine life and reduce maintenance cost",
        "to reduce fuel burn",
      ],
      answer: 2,
    },
    {
      id: 14,
      question: "Seasons are due to the:",
      options: [
        "inclination of the polar axis with the ecliptic plane",
        "Earth's elliptical orbit around the Sun",
        "Earth's rotation on its polar axis",
        "variable distance between Earth and Sun",
      ],
      answer: 0,
    },
    {
      id: 15,
      question: 'What is the meaning of the term ""standard time"" ?',
      options: [
        "It is the time set by the legal authorities for a country or part of a country",
        "It is the time zone system applicable only in the USA",
        "It is an expression for local mean time",
        "It is another term for UTC",
      ],
      answer: 0,
    },
    {
      id: 16,
      question: "The angle between True North and Magnetic North is called :",
      options: ["variation", "deviation", "compass error", "Drift"],
      answer: 0,
    },
    {
      id: 17,
      question:
        "When an aircraft on a westerly heading on the northern hemisphere accelerates, the effect of the acceleration error causes the magnetic compass to:",
      options: [
        "indicate a turn towards the north",
        "lag behind the turning rate of the aircraft",
        "indicate a turn towards the south",
        "to turn faster than the actual turning rate of the aircraft",
      ],
      answer: 0,
    },
    {
      id: 18,
      question: "An increase in pressure altitude causes?",
      options: [
        "An increase in CL",
        "A decrease in take-off distance",
        "An increase in take-off distance",
        "A decrease in CL",
      ],
      answer: 2,
    },
    {
      id: 19,
      question: "Long range cruise is a flight procedure which gives:",
      options: [
        "a specific range which is 99% of maximum specific range and a lower cruise speed",
        "a specific range which is about 99% of maximum specific range and higher cruise speed",
        "an IAS which is 1% higher than the IAS for maximum specific range",
        "a 1% higher TAS for maximum specific range",
      ],
      answer: 1,
    },
    {
      id: 20,
      question:
        "when cargo doors are operated using yellow electrical pump, flight controls are ?",
      options: [
        "fully operational",
        "inhibited, only alternate braking and eng 2 reverser are available",
        "no effect",
        "none of the above.",
      ],
      answer: 1,
    },
    {
      id: 21,
      question: "On the ECAM ELEC SD page DISC appears in amber ?",
      options: [
        "current is discharging at an abnormal rate",
        "The IDG is disconnected",
        "GEN 1 or GEN 2 are disconected",
        "BATT 1 and BATT 2 are disconnected",
      ],
      answer: 1,
    },
    {
      id: 22,
      question: "which computer monitors apu bleed?",
      options: ["BMC 1", "BMC 2", "ECB", "NONE OF THE ABOVE"],
      answer: 2,
      image: "https://cms-cdn.classplus.co/parserImages/e9f1c630-35d2-4b41-9176-a78a2dfe5c76.jpg",
    },
    {
      id: 23,
      question:
        "The landing gear indicator panel receives the information from micro switches and proximity detectors connected to:",
      options: ["BSCU", "LGCIU 2", "LGCIU 1", "BSCU and LGCIU 2"],
      answer: 2,
    },
    {
      id: 24,
      question: "A changeover between the two BSCU channels takes place when ?",
      options: [
        "at each DOWN landing gear lever selection.",
        "or in case one channel fails.",
        "both A & B",
        "at each UP landing gear lever selection, or in case one channel fails.",
      ],
      answer: 2,
    },
    {
      id: 25,
      question:
        "LDG GR safety valve automatically cuts off hydraulic supply to the landing gear system?",
      options: [
        "ADR 1 OR ADR3 indicate a speed greater than 260 kts",
        "main landing gear on the ground",
        "both a & b",
        "landing gear can be extended upto 280 kts",
      ],
      answer: 0,
    },
    {
      id: 26,
      question: "RAM AIR PB SW ON, delta p less than 1 psi. choose the correct statement?",
      options: [
        "The outflow valve opens to about 50 % when under automatic control.",
        "It does not automatically open when it is under manual control.",
        "Emergency ram airflow is directly supplied to the mixer unit",
        "all of the above.",
      ],
      answer: 3,
    },
    {
      id: 27,
      question:
        "What is course of action when FMGS information is not available for automatic pressurization?",
      options: [
        "Descend to 10,000ft",
        "Nothing as CPC2 will take over",
        "Select Manual Mode via Mode Selector Pushbutton to control outflow valve manually",
        "Use Landing Elevation Knob",
      ],
      answer: 3,
      image: "https://cms-cdn.classplus.co/parserImages/e0a93183-8be6-4d8b-b184-01ab9524576d.png",
    },
    {
      id: 28,
      question: "What is function of Safety valve?",
      options: [
        "It prevents excessive positive differential pressure",
        "It prevents excessive Negative differential pressure",
        "Its responsible for opening outflow Valve to relieve differential pressure",
        "both (A) and (B)",
      ],
      answer: 3,
    },
    {
      id: 29,
      question: "how is the auto brake activated ?",
      options: [
        "The command for ground spoilers extension is detected , for LO and MED mode",
        "The command for ground spoilers extension is detected, and the wheel speed is above 40 kt, for MAX mode",
        "both a & b",
        "auto brake is independent of ground spoiler command",
      ],
      answer: 2,
    },
    {
      id: 30,
      question: "Can APU be started when the RAT is stalled?",
      options: [
        "Yes, via AC static inverter bus",
        "Yes, via AC essential bus",
        "Yes, via gravity fuel feeding",
        "No, as APU requires AC power to start.",
      ],
      answer: 0,
    },
    {
      id: 31,
      question: "How are the hydraulic reservoir pressurized pneumatically ?",
      options: [
        "By APU bleed directly.",
        "By engine 2 bleed directly.",
        "By engine 1 bleed directly or cross bleed duct",
        "By engine 2 bleed directly or cross bleed duct.",
      ],
      answer: 2,
      image: "https://cms-cdn.classplus.co/parserImages/32880f8c-dbf0-4f9c-85e3-b4de09f95175.jpg",
    },
    {
      id: 32,
      question: "ILS 1 indications are displayed on ?",
      options: ["PFD 1 , ND 1", "PFD 2 ND 1", "PFD 1 ND 2", "PFD 2 ND 2"],
      answer: 2,
    },
    {
      id: 33,
      question: "If pilot uses the hand wheel / tiller and rudder at the same time?",
      options: [
        "hand wheel/tiller has priority",
        "rudder has priority",
        "inputs get cancelled",
        "inputs are algebrically/mathematically added",
      ],
      answer: 3,
    },
    {
      id: 34,
      question:
        "when one thrust lever is in CL or FLX/MCT detent and the other one is not in this detent, what indication would you get on the fma?",
      options: ["THR LCK", "TOGA LCK", "LVR ASYM", "LVR MCT"],
      answer: 2,
    },
    {
      id: 35,
      question: "ALPHA FLOOR IS ACTIVE FROM ?",
      options: ["Lift Off to 100 ft RA", "50 ft to 100 ft ra", "50 ft to landing", "lift off to landing"],
      answer: 0,
    },
    {
      id: 36,
      question:
        "What happens when landing elevation selector is not in auto position.",
      options: [
        "With FMGS available, landing elevation data is coming from FGMS for pressurization in controller, selected landing elevation is ignored.",
        "With the FMGS not available landing elevation selected is taken as reference.",
        "Landing elevation selected is taken as reference even if FMGS is available.",
        "Both (A) and (B) are correct.",
      ],
      answer: 2,
      image: "https://cms-cdn.classplus.co/parserImages/373a7b7d-b6ec-4a14-bc86-32ce717e5a1b.png",
    },
    {
      id: 37,
      question: "Two safety valves are provided such that",
      options: [
        "Each safety valve avoids excessive positive and negative differential pressure.",
        "One safety valve avoids excessive positive differential pressure and another safety valve avoids excessive negative differential pressure.",
        "Both safety valves avoid excessive positive differential pressure only.",
        "Both safety valves avoid excessive negative differential pressure only.",
      ],
      answer: 0,
      image: "https://cms-cdn.classplus.co/parserImages/6ffb27da-c091-4b80-80ce-464a382cf28e.jpg",
    },
    {
      id: 38,
      question: '"STOP RUDDER INPUT" (synthetic voice) ?',
      options: [
        "Inappropriate rudder pedal inputs detected in des at high speed. Message repeated at least TWO TIMES",
        "Inappropriate rudder pedal inputs detected in climb at high speed. Message repeated at least TWO TIMES",
        "Inappropriate rudder pedal inputs detected in cruise at high speed. Message repeated at least TWO TIMES",
        "Inappropriate rudder pedal inputs detected during t.o at high speed. Message repeated at least TWO TIMES",
      ],
      answer: 2,
    },
    {
      id: 39,
      question:
        "What does Airbus not recommend in INDEPENDENT MODE OPERATION of FMGC in flight?",
      options: [
        "DO NOT SWITCH the navigation databases.",
        "pulling one FMGC circuit breaker to force the system to operate in SINGLE mode.",
        "MAKE the same entries on both MCDUs to have both AP/FDs similar orders.",
        "none of the above",
      ],
      answer: 1,
    },
    {
      id: 40,
      question: "Which failures are inhibited in emer elec configuration?",
      options: [
        "PRIMARY FAILURES",
        "INDEPENDENT FAILURES",
        "SECONDARY FAILURES",
        "all failures are available on EWD",
      ],
      answer: 2,
    },
    {
      id: 41,
      question:
        "When is the thrust limit value indication not available on the top right corner of the EWD?",
      options: ["toga thrust", "idle reverse", "Flex thrust", "none of the above"],
      answer: 1,
    },
    {
      id: 42,
      question: "which of the following is not a thrust lever detent?",
      options: [
        "Max Cruise Thrust",
        "The Rev Idle (R or REV) detent",
        "The Climb (CL) detent",
        "The Maximum Continuous Thrust (MCT)/Flexible Take Off (FLX) detent",
      ],
      answer: 0,
    },
    {
      id: 43,
      question: "A fast IRS alignment can be performed?",
      options: [
        "if a complete IRS alignment is not necessary",
        "the difference between the IRS position and the FMGC position is at or above 5 NM (see MCDU POSITION MONITOR page)",
        "both a & b",
        "when flight needs to be dispatched on time.",
      ],
      answer: 2,
    },
    {
      id: 44,
      question: "mandatory reduction between gross flight path and net flight path?",
      options: ["2.1%", "1.2%", "0.8%", "3.2%"],
      answer: 2,
    },
    {
      id: 45,
      question: "Indicated Airspeed is ?",
      options: [
        "TAS corrected for density error",
        "EAS corrected for density error",
        "CAS corrected for temperature error",
        "CAS corrected for position error",
      ],
      answer: 3,
    },
    {
      id: 46,
      question: "GPWS SYS pushbutton OFF ?",
      options: [
        "Only Predictive GPWS functions are inhibited",
        "All basic GPWS alerts (Mode 1 to 5) are inhibited",
        "GPWS Mode 1 & 2 are inhibited",
        "GPWS mode 3 to 5 are inhibited",
      ],
      answer: 1,
    },
    {
      id: 47,
      question: "1FD1 indication on the FMA indicates?",
      options: [
        "FD 2 is off",
        "FMGC 2 has failed, FMGC 1 is active",
        "FMGC 1 has failed",
        "FD 1 is off",
      ],
      answer: 1,
    },
    {
      id: 48,
      question: "To allow cabin attendant announcements to be recorded on the CVR?",
      options: [
        "Nothing, they are automatically recorded",
        "Cabin has a dedicated voice recorder",
        "PA knob on ACP 3 ON, volume to full(at or above medium range)",
        "cabin announcements do not needed to be recorded.",
      ],
      answer: 2,
    },
    {
      id: 49,
      question: "safety valve automatically cuts off hydraulic supply to the landing gear system?",
      options: [
        "speed greater than 250 kts",
        "speed greater than 260 kts",
        "speed greater than 240 kts",
        "speed greater than 230 kts",
      ],
      answer: 1,
    },
    {
      id: 50,
      question:
        "Shorter distance in the arc along the equator between the prime meridean and the meridean through the point. Is defined as ?",
      options: ["LATITUDE", "LONGITUDE", "MERIDEAN", "VARIATION"],
      answer: 1,
    },
    {
      id: 51,
      question: "1 NAUTICAL MILE ?",
      options: [
        "is the length of arc of a great circle which subtends an arc of 1 minute at the centre of the curvature of earths surface",
        "one minute of latitude = 1 nautical mile",
        "one minute of longitude = 1 minute at the eqator only",
        "a nautical mile is shortest at the equator (6046ft) longest at the poles (6108 ft) because earth is flattened at the poles.",
        "all of the above",
      ],
      answer: 4,
    },
    {
      id: 52,
      question: "REGUL LO PR indication on DOOR OXY PAGE?",
      options: [
        "HP VALVE low pressure below 400 psi",
        "It is in amber, if oxygen pressure on the low-pressure circuit is low (50 PSI)",
        "SYS PB ON, CREW PB ON",
        "none of the above",
      ],
      answer: 1,
    },
    {
      id: 53,
      question: "When the BUSS is activated ?",
      options: [
        "The BUSS replaces the normal speed",
        "The GPS altitude replaces the barometric altitude scales.",
        "The BUSS is displayed on both PFDs when the flight crew turn off all ADRs.",
        "The BUSS information is based on the angle of attack (AOA), and depends on the slat/flap configuration",
        "ALL OF THE ABOVE",
      ],
      answer: 4,
    },
    {
      id: 54,
      question: "How does the RAT deploy automatically?",
      options: [
        "AC BUS 1 is not electrically supplied, and AC BUS 2 is not electrically supplied, and Aircraft speed is greater than 100 kt.",
        "blue hyd failure",
        "ac bus 1 fault",
        "emer elec panel",
      ],
      answer: 0,
    },
    {
      id: 55,
      question: "ASDR increases?",
      options: [
        "upslope runway",
        "down slope runway",
        "not effected by slope",
        "none of the above",
      ],
      answer: 1,
    },
    {
      id: 56,
      question: "what happens to the NWS atfer lift off?",
      options: [
        "rotates 90 degrees",
        "rotates 180 degrees",
        "An internal cam mechanism returns the nose wheel to the centered position after takeoff.",
        "retains the position at lift off",
      ],
      answer: 2,
    },
    {
      id: 57,
      question: "Mark the correct statement?",
      options: [
        "DC 2 SUPPLIES DC ESS",
        "TR 1 normally supplies DC ESS",
        "AC BUS 2 normally supplies AC ESS",
        "DC BUS 2 SUPPLIES DC BATT BUS",
      ],
      answer: 1,
    },
    {
      id: 58,
      question: "The length of clearway ?",
      options: ["500 ft", "1/2 of TORA", "1/4 of TORA", "None of the above"],
      answer: 1,
    },
    {
      id: 59,
      question: "When does DH on radio altimeter turn amber?",
      options: ["DH fail", "dh not entered on mcdu", "on reaching DH", "NONE of the above"],
      answer: 2,
    },
    {
      id: 60,
      question: "Where is GS mini dispalyed?",
      options: ["on PFD", "on ND", "on MCDU", "None of the above"],
      answer: 3,
    },
    {
      id: 61,
      question:
        "with APU bleed on and packs ON, what will be the effect on APU fuel consumption?",
      options: [
        "no effect",
        "increeased fuel consumption",
        "decreased fuel consumption",
        "none of the above",
      ],
      answer: 1,
    },
    {
      id: 62,
      question: "when one SFCC FAILS?",
      options: [
        "slats locked",
        "flaps locked",
        "slats/flaps operate at half speed",
        "no effect other SFCC takes over",
      ],
      answer: 2,
    },
  ],
};