import type { ExamData } from "../../exam-data";

export const examData: ExamData = {
    title: "Hydraulic System",
    questions: [{ id: 41, question: "The A320 has how many independent hydraulic systems?", options: ["1", "2", "3", "4"], answer: 2 },
    { id: 42, question: "Normal system pressure for all hydraulic systems is:", options: ["2500 psi", "2750 psi", "3000 psi", "3500 psi"], answer: 2 },
    { id: 43, question: "Green hydraulic system is powered by:", options: ["Engine 2 pump", "Engine 1 pump", "Electric pump", "RAT"], answer: 1 },
    { id: 44, question: "Yellow hydraulic system is powered in normal flight by:", options: ["Engine 1 pump", "Engine 2 pump", "Electric pump", "PTU"], answer: 1 },
    { id: 45, question: "Blue hydraulic system is powered by:", options: ["Engine 1 pump", "Engine 2 pump", "Electric pump", "PTU"], answer: 2 },
    { id: 46, question: "The PTU connects which systems?", options: ["Blue & Yellow", "Green & Blue", "Green & Yellow", "All three"], answer: 2 },
    { id: 47, question: "The PTU activates automatically when pressure difference exceeds approximately:", options: ["200 psi", "300 psi", "500 psi", "1000 psi"], answer: 2 },
    { id: 48, question: "The PTU is inhibited during:\n1. Cargo door operation\n2. Engine start\n3. Parking brake set & single engine\n4. During flight", options: ["1 only", "1 and 3", "2 only", "1,2,3"], answer: 1 },
    { id: 49, question: "Why is PTU inhibited during cargo door operation?", options: ["Prevent overheating", "Prevent uncommanded pressurization of Yellow system", "Prevent electrical overload", "To save fuel"], answer: 1 },
    { id: 50, question: "The RAT supplies hydraulic pressure to:", options: ["Green", "Yellow", "Blue", "All systems"], answer: 2 },
    { id: 51, question: "RAT deployment occurs automatically when:", options: ["Dual hydraulic failure", "Total AC electrical failure in flight", "Engine 1 failure", "Engine 2 failure"], answer: 1 },
    { id: 52, question: "When deployed, the RAT provides approximately:", options: ["1000 psi", "2000 psi", "3000 psi", "4000 psi"], answer: 2 },
    { id: 53, question: "In emergency electrical configuration, which primary flight controls remain available?\n1. Elevator\n2. Rudder\n3. Aileron\n4. Slats", options: ["1,2,3", "1,2", "1 only", "All four"], answer: 0 },
    { id: 54, question: "The Blue electric pump is powered by:", options: ["DC BUS 1", "DC BUS 2", "AC BUS 1", "AC BUS 2"], answer: 2 },
    { id: 55, question: "The Yellow electric pump is powered by:", options: ["DC BUS 1", "DC BUS 2", "AC BUS 1", "AC BUS 2"], answer: 3 },
    { id: 56, question: "Which system powers:\n1. Nose wheel steering\n2. Normal brakes", options: ["Blue", "Green", "Yellow", "All three"], answer: 1 },
    { id: 57, question: "Alternate brakes are powered by:", options: ["Green", "Yellow", "Blue", "RAT"], answer: 1 },
    { id: 58, question: "The brake accumulator is pressurized by:", options: ["Blue system", "Green system", "Yellow system", "RAT"], answer: 2 },
    { id: 59, question: "In case of Green hydraulic failure in flight:\nWhich systems are lost?\n1. Normal brakes\n2. Nose wheel steering\n3. PTU\n4. Landing gear extension", options: ["1,2", "1,2,4", "2,3", "All four"], answer: 1 },
    { id: 60, question: "If both Green and Yellow systems fail:", options: ["Blue powers landing gear", "Landing gear free-fall only", "RAT powers Green", "Brakes normal"], answer: 1 },
    { id: 61, question: "Landing gear normal extension is powered by:", options: ["Blue", "Yellow", "Green", "PTU"], answer: 2 },
    { id: 62, question: "Emergency landing gear extension uses:", options: ["Yellow pump", "Free-fall gravity", "RAT", "Blue system"], answer: 1 },
    { id: 63, question: "Combination Question:\nGreen system powers:\n1. Normal brakes\n2. Landing gear\n3. PTU\n4. Flaps", options: ["1,2,3", "1,2", "1,2,4", "All"], answer: 1 },
    { id: 64, question: "The reservoir is pressurized by:", options: ["Electrical compressor", "Engine bleed air", "Nitrogen bottle", "PTU"], answer: 1 },
    { id: 65, question: "Hydraulic fluid used is:", options: ["Skydrol", "MIL-H-5606", "Water-glycol", "Synthetic oil"], answer: 0 },
    { id: 66, question: "If Blue system fails in flight:\nWhich flight control redundancy is lost?", options: ["Elevator redundancy", "Rudder redundancy", "Aileron redundancy", "No major impact due to redundancy"], answer: 3 },
    { id: 67, question: "Why is Blue powered electrically instead of engine-driven?", options: ["Weight reduction", "Redundancy in dual engine failure", "Cost", "Fuel saving"], answer: 1 },
    { id: 68, question: "In flight, if Green system loses pressure and Yellow is normal:", options: ["PTU activates", "RAT deploys", "Blue pump stops", "AC ESS lost"], answer: 0 },
    { id: 69, question: "The PTU does NOT transfer:", options: ["Hydraulic fluid", "Mechanical power", "Pressure", "Torque"], answer: 0 },
    { id: 70, question: "During engine start with only one engine running:\nPTU may:", options: ["Remain OFF", "Automatically operate", "Deploy RAT", "Shut down Yellow"], answer: 1 }]
};